package com.peterchege.pinstagram.core.core_common

object TestTags {

    const val LOGIN_EMAIL_FIELD = "LOGIN_EMAIL_FIELD"
    const val LOGIN_PASSWORD_FIELD = "LOGIN_PASSWORD_FIELD"
    const val LOGIN_CIRCULAR_INDICATOR = "LOGIN_CIRCULAR_INDICATOR"

    const val FEED_LOADING_CIRCULAR_INDICATOR = "FEED_LOADING_CIRCULAR_INDICATOR"
    const val FEED_CONTAINER = "FEED_CONTAINER"
}