

name: Distribute Android App

on: [push]

jobs:
  distribute_android_app:
    runs-on: ubuntu-latest
    steps:
      - name: Create firebase distribution key  file
        run: |
          touch firebase_distribution_key.json
          echo ${{ secrets.FIREBASE_DISTRIBUTION_KEY }} >> firebase_distribution_key.json
          cat firebase_distribution_key.json
      - uses: finnp/create-file-action@master
          env:
            FILE_NAME: "firebase_distribution_key.json"
            FILE_DATA: ${{ secrets.FIREBASE_DISTRIBUTION_KEY }}
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install fastlane
        run: gem install fastlane
      - name: Distribute Android App
        run: |
          fastlane distribute
